/**
 * Each item a boss can drop
 */
export const bossLoot: Record<string, Array<string>> = {
  vigilant_guardian: [
    "ring",
    "feet",
    "legs",
    "chest",
    "head",
    "waist",
    "hands",
    "trinket",
    "one_hand",
    "off_hand",
  ],
  skolex_the_insatiable_ravener: [
    "back",
    "shoulder",
    "wrist",
    "waist",
    "trinket",
    "one_hand",
    "off_hand",
    "main_hand",
  ],
  artificer_xymox: [
    "neck",
    "feet",
    "waist",
    "shoulder",
    "hands",
    "wrist",
    "trinket1",
    "trinket2",
    "one_hand",
    "main_hand",
  ],
  dausegne_the_fallen_oracle: [
    "back",
    "chest",
    "waist",
    "shoulder",
    "feet",
    "head",
    "trinket",
    "one_hand",
    "main_hand",
  ],
  prototype_pantheon: [
    "feet",
    "head",
    "wrist",
    "chest",
    "trinket1",
    "trinket2",
    "main_hand",
  ],
  lihuvim_principal_architect: [
    "ring",
    "head",
    "legs",
    "waist",
    "wrist",
    "trinket",
  ],
  halondrus_the_reclaimer: [
    "ring",
    "feet",
    "trinket",
    "one_hand",
    "off_hand",
    "main_hand",
  ],
  anduin_wrynn: [
    "neck",
    "ring1",
    "ring2",
    "chest",
    "wrist",
    "waist",
    "trinket",
  ],
  lords_of_dread: [
    "back",
    "wrist",
    "hands",
    "trinket1",
    "trinket2",
    "main_hand",
    "off_hand",
  ],
  rygelon: [
    "ring",
    "feet",
    "wrist",
    "hands",
    "trinket",
    "one_hand",
    "main_hand",
  ],
  the_jailer: [
    "neck",
    "hands",
    "waist",
    "legs",
    "trinket",
    "one_hand",
    "off_hand",
    "main_hand",
  ],
};
